# AtCoder Beginner Contest 059

Created on November 17, 2020  

https://atcoder.jp/contests/abc059

## A（AC）

https://atcoder.jp/contests/abc059/tasks/abc059_a

In [7]:
S = list(input().split())

resident register number


In [8]:
print(*[s[0].upper() for s in S], sep="")

RRN


## B（AC, WA1回）

https://atcoder.jp/contests/abc059/tasks/abc059_b

In [22]:
A = input()
B = input()

123456789012345678901234567890
234567890123456789012345678901


In [24]:
lenA = len(A)
lenB = len(B)

ans = 'EQUAL'

if lenA > lenB:
    ans = 'GREATER'
elif lenA < lenB:
    ans = 'LESS'
else:
    for i in range(lenA):
        if int(A[i]) > int(B[i]):
            ans = 'GREATER'
            break
        elif int(A[i]) < int(B[i]):
            ans = 'LESS'
            break
            
print(ans)

LESS


## C（解けず）

https://atcoder.jp/contests/abc059/tasks/arc072_a

In [32]:
n = int(input())
a = list(map(int, input().split()))

4
1 -3 1 0


In [45]:
import numpy as np

b = a[:]
# b[2] += 2
# b[3] += 2

sum(b), np.cumsum(a),np.cumsum(np.cumsum(a)), np.cumsum(b),np.cumsum(np.cumsum(b))

(1,
 array([ 1, -2, -1, -1]),
 array([ 1, -1, -2, -3]),
 array([ 1, -2,  1,  1]),
 array([ 1, -1,  0,  1]))

## D（）

https://atcoder.jp/contests/abc059/tasks/abc059_d