# AtCoder Beginner Contest 177

Created on August 29, 2020  

https://atcoder.jp/contests/abc177

## A（AC）

https://atcoder.jp/contests/abc177/tasks/abc177_a

In [6]:
D, T, S = map(int, input().split())

10000 1 1


In [7]:
if D/S <= T:
    print("Yes")
else:
    print("No")

No


## B（AC）

https://atcoder.jp/contests/abc177/tasks/abc177_b

In [48]:
S = input()
T = input()

atcoder
btcodee


In [49]:
max_equal = 0

for i in range(len(S)-len(T)+1):
    tmp = 0
    for j in range(len(T)):
        tmp += (S[i:len(T)+i][j] == T[j])
    max_equal = max(max_equal, tmp)
    
print(len(T) - max_equal)

2


## C（AC、ただしTLE1回）

https://atcoder.jp/contests/abc177/tasks/abc177_c

In [47]:
N = int(input())
A = list(map(int, input().split()))

3
1 2 3


In [48]:
MOD = 10**9 + 7
A_mod = [a%MOD for a in A]

R = sum(A_mod)

ans = 0

for a in A_mod:
    R -= a
    ans = (ans + a%MOD * R%MOD)%MOD
    
print(ans)

11


以下、試行錯誤過程

In [41]:
MOD = 10**9 + 7
A_mod = [a%MOD for a in A]

ans = 0

for i in range(1, N):
    ans = (ans + A_mod[i-1]%MOD * sum(A_mod[i:])%MOD)%MOD
    
print(ans)

676688338


In [3]:
import itertools

MOD = 10**9 + 7
A_mod = [a%MOD for a in A]

combi = list(itertools.combinations(A_mod, 2))

ans = 0

for c in combi:
    ans += (c[0] * c[1]) % MOD
    
print(ans % MOD)

11


In [63]:
N = 10000
A = range(10000)

In [64]:
import numpy as np

mat = []
for i in range(1, N):
    mat.append([*[0]*i, *A_mod[:-i]])
    
ans = sum(np.array(mat) @ np.array(A_mod)%MOD)

print(ans % MOD)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 9999)

## D（）

https://atcoder.jp/contests/abc177/tasks/abc177_d

In [49]:
from ipywidgets import Textarea
import io

if 'open' in globals():
    del open
original_open = open
class custom_open():
    def __init__(self):
        self.text = ''
    def __call__(self, file, *args, **kwargs):
        if file == 0:
            return io.StringIO(self.text)
        return original_open(file, *args, **kwargs)
    def updater(self, change):
        self.text = change["new"]
open = custom_open()
text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)

Textarea(value='')

In [77]:
N, M, *_= list(map(int, open(0).read().split()))
AB = list(zip(*[map(int, iter(_))]*2))

In [78]:
AB

[(1, 2), (3, 4), (5, 1)]

In [80]:
import numpy as np
friend_flag = np.zeros(N*N).reshape(N, N)

In [89]:
for ab in AB:
    a,b = ab
    friend_flag[a-1][b-1] = 1
    friend_flag[b-1][a-1] = 1

In [90]:
print(friend_flag)

[[0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0.]]


In [92]:
friend_flag.sum(axis=0)

array([2., 2., 2., 2., 2.])