# AtCoder Beginner Contest 168

Created on May 17, 2020

https://atcoder.jp/contests/abc168

## A（AC）

https://atcoder.jp/contests/abc168/tasks/abc168_a

In [10]:
N = int(input())

183


In [11]:
if N%10 in [2,4,5,7,9]:
    print('hon')
elif N%10 in [0,1,6,8]:
    print('pon')
else:
    print('bon')

bon


## B（AC）

https://atcoder.jp/contests/abc168/tasks/abc168_b

In [17]:
K = int(input())
S = input()

40
ferelibenterhominesidquodvoluntcredunt


In [18]:
if len(S) <= K:
    print(S)
else:
    print(S[:K] + '...')

ferelibenterhominesidquodvoluntcredunt


## C（AC）

https://atcoder.jp/contests/abc168/tasks/abc168_c

In [33]:
A, B, H, M = map(int, input().split())

3 4 10 40


In [34]:
import math
import numpy as np

t = H + M/60
w_A = 2 * math.pi / 12 * t
w_B = 2 * math.pi * t

x_A = A * math.cos(w_A)
y_A = A * math.sin(w_A)

x_B = B * math.cos(w_B)
y_B = B * math.sin(w_B)

In [35]:
xy_A = np.array([x_A, y_A])
xy_B = np.array([x_B, y_B])

u = xy_A - xy_B

print(np.linalg.norm(u))

4.564257194330072


## D（復習）

https://atcoder.jp/contests/abc168/tasks/abc168_d

In [136]:
import numpy as np

N, M = map(int, input().split())
connections = np.array([[0 for i in range(N)] for j in range(N)])
for i in range(M):
    a, b = map(int, input().split())
    connections[a-1][b-1] = 1
    connections[b-1][a-1] = 1

6 9
3 4
6 1
2 4
5 3
4 6
1 5
6 2
4 5
5 6


In [145]:
for i in range(1, N+1):
    connections[i-1] *= i
    print(connections[i-1])

[0 0 0 0 1 1]
[0 0 0 2 0 2]
[0 0 0 3 3 0]
[0 4 4 0 4 4]
[5 0 5 5 0 5]
[6 6 0 6 6 0]


In [173]:
is_placed = [False]*(N-1)

next_rooms = np.where(connections[0]==1)[0]
rooms = next_rooms

num = {}

for room in rooms:
    num[room] = 1

ans = [0]*(N-1)

for i in range(1, N+1):
    if False in is_placed:
        rooms = next_rooms
        for room in rooms:
            ans[room] = num[room]
    else:
        break



IndexError: list assignment index out of range

In [133]:
if 0 in ans:
    print('No')
else:
    print('Yes')
    print(*ans, sep='\n')

Yes
16
16
4
1
1


In [169]:
np.where(connections[0]==1)[0]+1

array([5, 6])

In [171]:
connections

array([[0, 0, 0, 0, 1, 1],
       [0, 0, 0, 2, 0, 2],
       [0, 0, 0, 3, 3, 0],
       [0, 4, 4, 0, 4, 4],
       [5, 0, 5, 5, 0, 5],
       [6, 6, 0, 6, 6, 0]])

In [147]:
ans

[4, 4, 2, 1, 1]

In [138]:
N

6

In [139]:
tmp = connections

In [149]:
ans = [0]*(N-1)
ans

[0, 0, 0, 0, 0]

In [172]:
tmp

array([[0, 0, 0, 0, 1, 1],
       [0, 0, 0, 2, 0, 2],
       [0, 0, 0, 3, 3, 0],
       [0, 4, 4, 0, 4, 4],
       [5, 0, 5, 5, 0, 5],
       [6, 6, 0, 6, 6, 0]])